# This is a JSON Schema file for the channel configuration.
# http://json-schema.org/understanding-json-schema/
# It's written in YAML, but the structure is the same.

# Definitions can go here to keep the structure clean.
definitions:
  directionality: &directionality
    - Bidirectional
    - SpaceToEarth
    - EarthToSpace
  # ISO 3166 country codes
  iso3166: &iso3166
    - AD # Andorra
    - AE # United Arab Emirates
    - AF # Afghanistan
    - AG # Antigua and Barbuda
    - AI # Anguilla
    - AL # Albania
    - AM # Armenia
    - AO # Angola
    - AQ # Antarctica
    - AR # Argentina
    - AS # American Samoa
    - AT # Austria
    - AU # Australia
    - AW # Aruba
    - AX # Åland Islands
    - AZ # Azerbaijan
    - BA # Bosnia and Herzegovina
    - BB # Barbados
    - BD # Bangladesh
    - BE # Belgium
    - BF # Burkina Faso
    - BG # Bulgaria
    - BH # Bahrain
    - BI # Burundi
    - BJ # Benin
    - BL # Saint Barth
    - BM # Bermuda
    - BN # Brunei Darussalam
    - BO # Bolivia
    - BQ # Bonaire
    - BR # Brazil
    - BS # Bahamas
    - BT # Bhutan
    - BV # Bouvet Island
    - BW # Botswana
    - BY # Belarus
    - BZ # Belize
    - CA # Canada
    - CC # Cocos
    - CD # Congo
    - CF # Central African Republic
    - CG # Congo
    - CH # Switzerland
    - CI # Côte d'Ivoire
    - CK # Cook Islands
    - CL # Chile
    - CM # Cameroon
    - CN # China
    - CO # Colombia
    - CR # Costa Rica
    - CU # Cuba
    - CV # Cabo Verde
    - CW # Curaçao
    - CX # Christmas Island
    - CY # Cyprus
    - CZ # Czechia
    - DE # Germany
    - DJ # Djibouti
    - DK # Denmark
    - DM # Dominica
    - DO # Dominican Republic
    - DZ # Algeria
    - EC # Ecuador
    - EE # Estonia
    - EG # Egypt
    - EH # Western Sahara
    - ER # Eritrea
    - ES # Spain
    - ET # Ethiopia
    - FI # Finland
    - FJ # Fiji
    - FK # Falkland Islands
    - FM # Micronesia
    - FO # Faroe Islands
    - FR # France
    - GA # Gabon
    - GB # United Kingdom of Great Britain and Northern Ireland
    - GD # Grenada
    - GE # Georgia
    - GF # French Guiana
    - GG # Guernsey
    - GH # Ghana
    - GI # Gibraltar
    - GL # Greenland
    - GM # Gambia
    - GN # Guinea
    - GP # Guadeloupe
    - GQ # Equatorial Guinea
    - GR # Greece
    - GS # South Georgia and the South Sandwich Islands
    - GT # Guatemala
    - GU # Guam
    - GW # Guinea
    - GY # Guyana
    - HK # Hong Kong
    - HM # Heard Island and McDonald Islands
    - HN # Honduras
    - HR # Croatia
    - HT # Haiti
    - HU # Hungary
    - ID # Indonesia
    - IE # Ireland
    - IL # Israel
    - IM # Isle of Man
    - IN # India
    - IO # British Indian Ocean Territory
    - IQ # Iraq
    - IR # Iran
    - IS # Iceland
    - IT # Italy
    - JE # Jersey
    - JM # Jamaica
    - JO # Jordan
    - JP # Japan
    - KE # Kenya
    - KG # Kyrgyzstan
    - KH # Cambodia
    - KI # Kiribati
    - KM # Comoros
    - KN # Saint Kitts and Nevis
    - KP # Korea
    - KR # Korea
    - KW # Kuwait
    - KY # Cayman Islands
    - KZ # Kazakhstan
    - LA # Lao People's Democratic Republic
    - LB # Lebanon
    - LC # Saint Lucia
    - LI # Liechtenstein
    - LK # Sri Lanka
    - LR # Liberia
    - LS # Lesotho
    - LT # Lithuania
    - LU # Luxembourg
    - LV # Latvia
    - LY # Libya
    - MA # Morocco
    - MC # Monaco
    - MD # Moldova
    - ME # Montenegro
    - MF # Saint Martin
    - MG # Madagascar
    - MH # Marshall Islands
    - MK # North Macedonia
    - ML # Mali
    - MM # Myanmar
    - MN # Mongolia
    - MO # Macao
    - MP # Northern Mariana Islands
    - MQ # Martinique
    - MR # Mauritania
    - MS # Montserrat
    - MT # Malta
    - MU # Mauritius
    - MV # Maldives
    - MW # Malawi
    - MX # Mexico
    - MY # Malaysia
    - MZ # Mozambique
    - NA # Namibia
    - NC # New Caledonia
    - NE # Niger
    - NF # Norfolk Island
    - NG # Nigeria
    - NI # Nicaragua
    - NL # Netherlands
    - NO # Norway
    - NP # Nepal
    - NR # Nauru
    - NU # Niue
    - NZ # New Zealand
    - OM # Oman
    - PA # Panama
    - PE # Peru
    - PF # French Polynesia
    - PG # Papua New Guinea
    - PH # Philippines
    - PK # Pakistan
    - PL # Poland
    - PM # Saint Pierre and Miquelon
    - PN # Pitcairn
    - PR # Puerto Rico
    - PS # Palestine
    - PT # Portugal
    - PW # Palau
    - PY # Paraguay
    - QA # Qatar
    - RE # Réunion
    - RO # Romania
    - RS # Serbia
    - RU # Russian Federation
    - RW # Rwanda
    - SA # Saudi Arabia
    - SB # Solomon Islands
    - SC # Seychelles
    - SD # Sudan
    - SE # Sweden
    - SG # Singapore
    - SH # Saint Helena
    - SI # Slovenia
    - SJ # Svalbard and Jan Mayen
    - SK # Slovakia
    - SL # Sierra Leone
    - SM # San Marino
    - SN # Senegal
    - SO # Somalia
    - SR # Suriname
    - SS # South Sudan
    - ST # Sao Tome and Principe
    - SV # El Salvador
    - SX # Sint Maarten
    - SY # Syrian Arab Republic
    - SZ # Eswatini
    - TC # Turks and Caicos Islands
    - TD # Chad
    - TF # French Southern Territories
    - TG # Togo
    - TH # Thailand
    - TJ # Tajikistan
    - TK # Tokelau
    - TL # Timor
    - TM # Turkmenistan
    - TN # Tunisia
    - TO # Tonga
    - TR # Turkey
    - TT # Trinidad and Tobago
    - TV # Tuvalu
    - TW # Taiwan
    - TZ # Tanzania
    - UA # Ukraine
    - UG # Uganda
    - UM # United States Minor Outlying Islands
    - US # United States of America
    - UY # Uruguay
    - UZ # Uzbekistan
    - VA # Holy See
    - VC # Saint Vincent and the Grenadines
    - VE # Venezuela
    - VG # Virgin Islands
    - VI # Virgin Islands
    - VN # Viet Nam
    - VU # Vanuatu
    - WF # Wallis and Futuna
    - WS # Samoa
    - YE # Yemen
    - YT # Mayotte
    - ZA # South Africa
    - ZM # Zambia
    - ZW # Zimbabwe
  # Regular expression for 'humantime' formatted durations
  humantime: &humantime ^([0-9]+ *(?:nsec|ns|usec|us|msec|ms|seconds|second|sec|s|minutes|minute|min|m|hours|hour|hr|h|days|day|d|weeks|week|w|months|month|M|years|year|y) *)+$
  link_profile: &link_profile
    type: array
    minItems: 1
    items:
      type: object
      additionalProperties: false
      properties:
        min_elevation_deg:
          minimum: 0
          maximum: 90
          type: integer
        downlink_rate_kbps:
          minimum: 0
          type: number
        uplink_rate_kbps:
          minimum: 0
          type: number
        min_duration:
          type: string
          pattern: *humantime
      required:
        - min_elevation_deg
        - downlink_rate_kbps
        - uplink_rate_kbps

  channel_parameter_set: &channel_parameter_set
    oneOf:
      - type: object
        properties:
          radio_band:
            const: UHF
        required:
          - radio_band
      - type: object
        # note: satellite parameters
        properties:
          radio_band:
            enum: [SBAND, XBAND]
          protocol:
            enum: [DVBS2X, LEGACY]
          bandaid_mode:
            type: string
          bandaid_override:
            type: object
            additionalProperties: true
          bandaid_global_params:
            type: object
            additionalProperties: true
          use_radionet:
            type: boolean
          # note: gs parameters
          ground_override:
            type: object
            additionalProperties: true
  chain_override: &chain_override
    type: object
    additionalProperties: true

  window_parameters: &window_parameters
    type: object
    properties:
      forward_channels:
        type: array
        items: *channel_parameter_set
      reverse_channels:
        type: array
        items: *channel_parameter_set
      # note the property here has nonstandard capitalization.  Used in MissionNetwork
      chainOverride: *chain_override

  contact_type: &contact_type ^CONTACT_[A-Z0-9_]+$

# Basic properties which are shared between both satellite and ground station schemas.
base_properties: &base_properties
  legal:
    type: boolean
  enabled:
    type: boolean
  directionality:
    enum: *directionality
  contact_type:
    type: string
    pattern: *contact_type
  contact_overhead_time:
    type: string
    pattern: *humantime
  allowed_license_countries:
    type: array
    items:
      type: string
      enum: *iso3166
  link_profile: *link_profile
  window_parameters: *window_parameters

# Modifiers for separation constraints
modifier: &constraint_modifier
  type: object
  additionalProperties: false
  properties:
    only_for_ground_stations:
      type: array
      items:
        type: string

geodetic_coordinate: &geodetic_coordinate
  type: object
  additionalProperties: false
  properties:
    # Geodetic longitude in degrees, with East positive, West negative.
    # NOTE This is different from the representation TK uses, where West is positive.
    longitude:
      type: number
    # Geodetic latitude in degrees, with North positive, South negative.
    latitude:
      type: number
    # Elevation above WGS84 reference ellipsoid in meters.
    elevation_m:
      type: number

# The full JSON schema for both satellites and ground stations.
schema:
  oneOf:
    # Ground station schema
    - type: object
      additionalProperties: false
      properties:
        <<: *base_properties
        dynamic_window_parameters:
          type: object
          additionalProperties: false
          properties:
            transmit_times:
              type: object
              additionalProperties: false
              properties:
                elevation_threshold_deg:
                  type: number
              required:
                - elevation_threshold_deg
        ground_station_constraints:
          type: object
          properties:
            deny_satellites:
              type: array
              items:
                type: string
            fixed_contact_duration:
              type: array
              items:
                type: string
                pattern: *humantime
              optional: true
            dollar_cost:
              type: object
              additional_properties: false
              optional: true
              properties:
                time_dollar_cost:
                  type: object
                  additional_properties: false
                  properties:
                    dollars:
                      type: number
                    interval:
                      type: string
                      pattern: *humantime
                fixed_dollar_cost:
                  type: number
          additionalProperties: false
      required:
        - legal
        - enabled
        - directionality
        - contact_overhead_time
        - allowed_license_countries
        - ground_station_constraints
        - link_profile

    # Satellite schema
    - type: object
      additionalProperties: false
      properties:
        <<: *base_properties
        satellite_constraints:
          type: object
          additionalProperties: false
          properties:
            max_contact_time:
              type: object
              additionalProperties: false
              optional: true
              properties:
                amount:
                  type: string
                  pattern: *humantime
                interval:
                  type: string
                  pattern: *humantime
            budget_name:
              type: string
            deny_ground_stations:
              type: array
              items:
                type: string
            sun_constraint:
              type: object
              additionalProperties: false
              optional: true
              properties:
                contacts_above_threshold:
                  type: boolean
                exclude_gs_ids:
                  type: array
                  items:
                    type: string
                declination_threshold_deg:
                  type: number
                pre_buffer:
                  type: string
                  optional: true
                  pattern: *humantime
                post_buffer:
                  type: string
                  optional: true
                  pattern: *humantime
            separation:
              type: array
              items:
                anyOf:
                  - type: object
                    additionalProperties: false
                    properties:
                      type:
                        type: string
                        enum: [minimum_distance]
                      norad_id:
                        type: number
                      distance_m:
                        type: number
                      modifier: *constraint_modifier
                  - type: object
                    additionalProperties: false
                    properties:
                      type:
                        type: string
                        enum: [no_overlapping_transits]
                      norad_id:
                        type: number
                      modifier: *constraint_modifier
                  - type: object
                    additionalProperties: false
                    properties:
                      type:
                        type: string
                        enum: [minimum_angular_separation]
                      norad_id:
                        type: number
                      angle_deg:
                        type: number
                      modifier: *constraint_modifier
                  - type: object
                    additionalProperties: false
                    properties:
                      type:
                        type: string
                        enum: [avoid_ground_station_beams]
                      norad_ids:
                        type: array
                        items:
                          type: number
                      station_coordinates:
                        type: array
                        items: *geodetic_coordinate
                      beamwidth_deg:
                        type: number
                      modifier: *constraint_modifier
      required:
        - legal
        - enabled
        - directionality
        - contact_overhead_time
        - allowed_license_countries
        - satellite_constraints
        - link_profile
