fragments:
  aws_login: &aws_creds
    aws_access_key_id: ((ecr_credentials.aws_access_key_id))
    aws_secret_access_key: ((ecr_credentials.aws_secret_access_key))
    aws_region: us-gov-west-1

  dockerhub_login: &docker_hub
    username: ((docker.docker-hub-username))
    password: ((docker.docker-hub-token))

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource
      tag: v0.23.0
      <<: *docker_hub

resources:
  - name: repo
    type: pull-request
    icon: source-branch
    webhook_token: 1208FE9D-C3A4-434D-BF57-9E1A539445B3
    source:
      repository: space/channel-config
      access_token: ((optimizer-team.github_access_token))
      v3_endpoint: https://github.ect.spire.com/api/v3/
      v4_endpoint: https://github.ect.spire.com/api/graphql
      disable_git_lfs: true

jobs:
  - name: build
    on_failure:
      put: repo
      inputs: [repo]
      params:
        path: repo
        status: failure
      get_params: {skip_download: true}
    on_success:
      put: repo
      inputs: [repo]
      params:
        path: repo
        status: success
      get_params: {skip_download: true}
    plan:
      - get: repo
        trigger: true
        version: every
      - put: concourse-status-update
        resource: repo
        inputs: [repo]
        params: {path: repo, status: pending}
        get_params: {skip_download: true}
      - task: test
        privileged: true
        file: repo/ci/test-task.yml
        input_mapping:
          repo: repo