name: "Manual - Sync dashboards"

concurrency: 1
on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: [ self-hosted ]

    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v4
        with:
          # fetch the last 2 commits on the branch so we can tell what files changed
          ref: ${{ github.ref_name }}
          fetch-depth: 2

      - run: |-
          # Export Dashboards, create PR  
          dt=$(date +'%Y-%m-%d %H:%M:%S')
          # Install dependencies
          apt-get install jq
          pip install --upgrade pip poetry
          poetry install
        
          # Create unique branch name
          BRANCH_NAME="populate-per-pair-elevations-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME
        
          # Commit and push changes
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add json
          git add yaml
          
          # Run optimize populate tool
          python populate_per_pair_elevations.py
                  
          # Check if there are any changes to commit
          if ! git diff --staged --quiet; then
            echo "Changes detected, creating commit..."
            git commit -m "Per pair elevation optimization automated update - ${dt}"
            git push origin $BRANCH_NAME        
          else
            # 5.1. Do nothing
            echo "No changes detected, skipping commit"
          fi
        working-directory: bundles/Project Ripley/dashboards
        env:
          DATABRICKS_HOST:  "https://dbc-24e0a945-16d8.cloud.databricks.us"
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_BUNDLE_ENV: dev
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

